tango_with_django_project17/rango/urls.py
__author__ = 'arshad'
from django.conf.urls import patterns,url
from rango import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^category/(?P<cat_name_slug>[\w\-]+)/$', views.category, name='category'),
                       url(r'^about/', views.about, name='about'),
                       url(r'^add_category/$', views.add_category, name='add_category'),
                       url(r'^category/(?P<cat_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
                       url(r'^goto/$', views.track_url, name='goto'),
                       url(r'^login/$', views.user_login, name='user_login'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^your_name/$', views.your_name, name='your_name'),
                       url(r'^contact_us/$', views.contactFormView, name='contact_us'),
                       url(r'^search/$', views.search, name='search'),
                       url(r'^deals/$', views.getDeals, name='deals'),
                       url(r'^like_category/$', views.like_category, name='like_category'),
                       #url(r'^sample_form/$', views.sample_form, name='sample_form'),

)

tango_with_django_project17/tango_with_django_project17/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'
    #def get_success_url(self, request, user):
    #    return '/rango/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_django_project17.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('rango.urls')),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)


if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

tango_with_django_project17/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    #additional attributes we wish to include
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username

tango_with_django_project17/rango/forms.py
__author__ = 'arshad'
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page
        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them...
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        #or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not ( url.startswith('http://') or url.startswith('https://')) :
            url = 'http://' + url
            cleaned_data['url'] = url
        return cleaned_data


# simple form
class NameForm(forms.Form):
    your_nam = forms.CharField(label="Your Name", max_length=100)

# contact me functionality form
class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField
    cc_myself = forms.BooleanField(required=False)


#one for the base user class
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project17/rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category,Page
from rango.forms import CategoryForm, PageForm, NameForm, ContactForm, UserForm, UserProfileForm
from utils import send_email, run_query
from google_search import getSearchUrls
from DealScraper import get_deals_from_hof
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
import time
## dd/mm/yyyy f
# Create your views here.

CACHE = {}
def index(request):
    #return HttpResponse("Rango Says Hello World")
    #request.session.set_test_cookie()
    #category_list = Category.objects.order_by('-likes')[:5]
    category_list = Category.objects.all()
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'boldmessage':"I am bold arshad from the context",
                    'categories':category_list, 'pages':page_list}

    # Get the number of visits to the site.
    # We use the COOKIES.get() function to obtain the visits cookie.
    # If the cookie exists, the value returned is casted to an integer.
    # If the cookie doesn't exist, we default to zero and cast that.

    visits = request.session.get('visits')
    if not visits:
        visits = 1
    reset_last_visit = False
    last_visit = request.session.get('last_visit')
    #response = render(request, 'rango/index.html', context_dict)

    # does the cookie last_visit exists
    if last_visit:
        #if it does get the cookies value
        #cast it to python data time object
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")
        # if its more than a day since the last visit
        if (datetime.now() - last_visit_time).seconds > 0:
            visits += 1
            reset_last_visit = True
    else:
        # last_visit cookie doesnt exist
        reset_last_visit = True

    if reset_last_visit:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits

    context_dict['visits'] = visits
    response = render(request, 'rango/index.html', context_dict)
    #return render(request, 'rango/index.html', context_dict)
    return response


def about(request):
    # If the visits session varible exists, take it and use it.
# If it doesn't, we haven't visited the site so set the count to zero.
    if request.session.get('visits'):
        count = request.session.get('visits')
    else:
        count = 0

    #return HttpResponse("About rango mmm lemme think")
    return render(request, 'rango/about.html', {'count':count})



def category(request, cat_name_slug):

    context_dict = {}
    context_dict['result_list'] = None
    context_dict['query'] = None
    if request.method == 'POST':
        query = request.POST.get('query')
        if query:
            context_dict['query'] = query.strip()
            result_list = getSearchUrls(query)
            context_dict['result_list'] = result_list
    try:
        category = Category.objects.get(slug=cat_name_slug)
        context_dict['category'] = category
        context_dict['category_name'] = category.name
        context_dict['slug_category_name'] = cat_name_slug
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
    except Category.DoesNotExist:
        pass
    if not context_dict['query']:
        context_dict['query'] = category.name
    return render(request, 'rango/category.html',context_dict)

@login_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # have we been provided with valid form
        if form.is_valid():
            form.save(commit=True)
            #call index view which is home page
            return index(request)
        else:
            print form.errors
    else:
        #if not post request display the form again
        form = CategoryForm()
    return render(request, 'rango/add_category.html', {'form':form})
#add page view

@login_required
def add_page(request, cat_name_slug):
    try:
        cat = Category.objects.get(slug=cat_name_slug)
    except Category.DoesNotExist:
        cat = None

    if request.method == 'POST':
        pageForm = PageForm(request.POST)
        if pageForm.is_valid():
            print 'page form is valid'
            if cat:
                page = pageForm.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()

                #use a redirct here
                return category(request, cat_name_slug)
        elif request.POST.get('url') and request.POST.get('title'):
            if cat:
                title = request.POST.get('title').strip()
                url = request.POST.get('url').strip()
                newPage = Page.objects.get_or_create(category=cat, title=title)[0]
                newPage.url = url
                newPage.views = 0
                newPage.save()
                return category(request, cat_name_slug)
        else:
            print 'Errro in page form', pageForm.errors
    else:
        pageForm = PageForm()
    context_dict = {'form':pageForm, 'category':cat}
    return render(request, 'rango/add_page.html', context_dict)



def your_name(request):
    if request.method == 'POST':
        nameForm = NameForm(request.POST)
        if nameForm.is_valid():
            category_list = Category.objects.order_by('-likes')[:5]
            context_dict = {'boldmessage':"I am bold arshad from the context",
                    'categories':category_list}
            yourName = nameForm.cleaned_data['your_nam'].encode('UTF-8')
            context_dict['yourName'] = yourName
            return render(request, 'rango/index.html', context_dict)

            #print nameForm.cleaned_data
            #print 'Content ', nameForm.cleaned_data['your_nam'].encode('UTF-8')
            #process the data in form.cleaned_data
            return HttpResponse("Thanks for submitting a form")
    else:
        form = NameForm()
        context_dict = {}
        #category_list = Category.objects.order_by('-likes')[:5]
        #context_dict = {'boldmessage':"I am bold arshad from the context",'categories':category_list}
        context_dict['form'] = form
    return render(request, 'rango/your_name.html', context_dict)


def contactFormView(request):
    if request.method == 'POST':
        contactForm = ContactForm(request.POST)
        if contactForm.is_valid():
            subject = contactForm.cleaned_data['subject']
            message = contactForm.cleaned_data['message']
            sender = contactForm.cleaned_date['sender']
            cc_myself = contactForm.cleaned_data['cc_myself']
            recipients = ['arshad2k7@gmail.com']
            if cc_myself:
                recipients.append(sender)
            #send_email(recipients)
            return HttpResponse("Inside contact form")
    else:
        contactForm = ContactForm()
        context_dict = {}
        context_dict['form'] = contactForm
    return render(request, 'rango/contactus_form.html', {'form': contactForm})
        #return HttpResponse("Inside contact form")

# commenting out as we use django ap redux to manage login and logout
def register(request):

    registered = False
    context_dict = {}
    if request.method == 'POST':
        userForm = UserForm(data=request.POST)
        userProfileForm = UserProfileForm(data=request.POST)

        if userForm.is_valid() and userProfileForm.is_valid():
            user = userForm.save()
            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()
            #now sort out the profile form
            profile = userProfileForm.save(commit=False)
            profile.user = user
            #save use profile model instance
            profile.save()
            registered = True
        else:
            print userForm.errors, userProfileForm.errors
    else:
        userForm = UserForm()
        userProfileForm = UserProfileForm()
        #context_dict = {'user_form':userForm, 'profile_form':UserProfileForm, 'registered':registered}
    return render(request, 'rango/register.html', {'user_form':userForm, 'profile_form':UserProfileForm, 'registered':registered})


def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/rango/')
            else:
                # Bad login details were provided. So we can't log the user in.
                print "Invalid login details: {0}, {1}".format(username, password)
                return HttpResponse("Invalid login details supplied.")

    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'rango/login.html', {})

# Use the login_required() decorator to ensure only those logged in can access the view.

@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/rango/')


def search(request):
    print 'inside search'
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()

tango_with_django_project17/templates/rango/about.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}About Page{% endblock %}

{% block body_block %}
<div class="page-header">
                <h1>About</h1>
            </div>
            <div>
            <p></strong>.</p>

            <img  width="90" height="100" src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /> <!-- New line -->
            </div>

        <strong> Rango says: Here is the about page.</strong> <a href="/rango/">Index</a>
        <strong> BTW, number of times you visited rango was {{ count }}</strong>

        <button class="ouch">
            Click Me - I run the Javascript
        </button>
{% endblock %}

tango_with_django_project17/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Add Category Page{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
    <h1> Add a Category </h1>
    <form id="category_form" method="POST" action="{% url 'add_category' %}">

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category"/>

    </form>

    {% else %}
    <h1> Only Registered Users can add/create categories sorry please register </h1>
    <a href="/rango/register/">Register Here</a><br/>
    {% endif %}

{% endblock %}

tango_with_django_project17/templates/rango/base.html
!DOCTYPE html>

{% load staticfiles %}


<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>

    <link href="https://getbootstrap.com/docs/3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/3.3/examples/dashboard/dashboard.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/3.3/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
     <!--script src="{% static 'js/jquery-1.11.1.js' %}"></script-->
      <!--script src="{% static 'js/popper.js' %}"></script-->
      <script src="{% static 'js/jquery.js' %}"></script>
     <script src="{% static 'js/rango-jquery.js' %}"></script>
     <script src="{% static 'js/rango-ajax.js' %}"></script>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/rango/">Rango</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'index' %}">Home</a></li>
                    {% if user.is_authenticated %}

                        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li><a href="{% url 'add_category' %}">Add a New Category</a></li>
                    {% else %}
                        <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                        <li><a href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                <!--li><a href="{% url 'search' %}">Search</a></li-->
                <li><a href="{% url 'deals' %}">Find Best Deals</a></li>
                <li><a href="{% url 'about' %}">About</a></li>

              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
          {% load rango-extras %}
        <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}
                    {% get_category_list category %}
                {% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
           </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://getbootstrap.com/docs/3.3/dist/js/bootstrap.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

tango_with_django_project17/templates/rango/base_old.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Rango - {% block title %} How to tango with django! {% endblock %}</title>
</head>
<body>
    <div>
        {% block body_block %} {% endblock %}
    </div>
    <hr />

    <div>
        <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                <li><a href="{% url 'add_category' %}">Add a New Category</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}

                <!-- li><a href="/rango/about/"> About </a></li-->
                <li><a href="{% url 'about' %}"> About </a></li>
                <li><a href="{% url 'your_name' %}">Add a Your Name</a></li>
                <li><a href="{% url 'contact_us' %}">Contact Us</a></li>
        </ul>
    </div>


</body>
</html>

tango_with_django_project17/templates/rango/category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}{{ category.name }}{% endblock %}

{% block body_block %}
        {% if category %}
            <h1> {{ category_name }} </h1>

        <!-- Like Button -->
        <p>

        <strong id="like_count">{{ category.likes }}</strong> people like this category

        {% if user.is_authenticated %}
                <button id="likes" data-catid="{{category.id}}" class="btn btn-primary" type="button">
                <span class="glyphicon glyphicon-thumbs-up"></span>
                Like
                </button>
        {% endif %}

        </p>

            {% if pages %}
                <ul>
                    {% for page in pages %}
                    <!--li> <a href="{{ page.url }}"> {{ page.title }}</a> </li-->
                    <li> <a href="{% url 'goto' %}?page_id={{ page.id }}"> {{ page.title }}</a>
                    {% if page.views > 1 %}
                        ( {{ page.views }} views )
                    {% elif pag.views == 1 %}
                        ( {{ page.views }} view)
                    {% endif %}
                    </li>
                    {% endfor %}
                </ul>

                <!-- Genric search for category -->
             <form class="form-inline" id="user_form" method="post" action="{% url 'category'  category.slug %}">
                {% csrf_token %}

                <input class="form-control" type="text" size="50" name="query" value="{{query}}" id="query" />
                <input class="btn btn-primary" type="submit" name="submit" value="Search" />
                <br />
            </form>

            <div class="panel">
                {% if result_list %}
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            Results
                        </h3>
                        <div class="panel-body">
                            <div class="list-group">
                                {% for result in result_list %}

                                    <div class="list-group-item">
                                        <h4 class="list-group-item-heading"><a href="{{ result.url }}"> {{ result.title }} </a> </h4>
                                        <p class="list-group-item-text">{{ result.summary }}</p>
                                        <form class="form-inline" id="addpage{{result.title}}" method="post" action="{% url 'add_page'  category.slug %}">
                                            {% csrf_token %}
                                            <input id="id_title" type = "hidden" maxlength="128" name="title" type="text" value="{{ result.title }}">
                                            <input id="id_url" type = "hidden" maxlength="200" name="url" type="url" value="{{ result.url }}">
                                            <input class="btn btn-primary" type="submit" name="submit" value="AddThisPage" />
                                        </form>
                                    </div>

                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>

            {% else %}
                <strong> No pages currently in category.</strong>
            {% endif %}

           {% if user.is_authenticated %}
            <!--a href="/rango/category/{{ slug_category_name }}/add_page">Add a New Page</a><br /-->
            <a href="{% url 'add_page' slug_category_name %}">Add a New Page</a><br />
           {% endif %}
        {% else %}
            The specified category {{ slug_category_name }} does not exist!
        {% endif %}


{% endblock %}

tango_with_django_project17/templates/rango/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
    {% for c in cats %}
        {% if c == act_cat %} <li class="active"> {% else %} <li> {% endif %}
        <a href="{% url 'category'  c.slug %}">{{ c.name }}</a></li>
    {% endfor %}

{% else %}
    <li> <strong >There are no category present.</strong></li>

    </ul>
{% endif %}

tango_with_django_project17/templates/rango/contactus_form.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Contact Us{% endblock %}

{% block body_block %}

     <h1> Contact US </h1>

    <form action="{% url 'contact_us' %}" method="POST">
    {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>

    <tr><input type="submit" value="Submit" /></tr>

    </form>
{% endblock %}

tango_with_django_project17/templates/rango/deals.html
{% extends 'rango/base.html' %}

{% load staticfiles %}


{% block body_block %}

             <!-- Genric search for category -->
             <form class="form-inline" id="user_form" method="post" action="{% url 'deals' %}">
                {% csrf_token %}
                Sex(male , female):
                <input class="form-control" type="text" size="50" name="sex"  value = "male" id="sex" />
                Discount:
                <input class="form-control" type="text" size="50" name="disc" id="disc" />

                <input class="btn btn-primary" type="submit" name="submit" value="GetDeals" />
                <br />
            </form>


     {% if deals %}
        <div class="container">
        <table class="table table-striped">

            <tr>
                <th> Item Name </th>
                <th> Old Price </th>
                <th> New Price </th>
                <th> Discount </th>
            </tr>
          {% for deal in deals %}
           <tr>
                <td> {{ deal.title }} </td>
                <td> {{ deal.wasprice }} </td>
                <td> {{ deal.nowprice }} </td>
               <td> {{ deal.discount }} </td>
            </tr>
           {% endfor %}

        </table>
        </div>
     {% else %}
                <strong> No deals currently in display.</strong>
     {% endif %}

{% endblock %}

tango_with_django_project17/templates/rango/error.html
{% extends 'rango/base.html' %}

{% block title %} Error page {% endblock %}

{% block body_block %}
    <div class="container well">
    <p> ERROR: {{ error }}</p>
    </div>
{% endblock %}

tango_with_django_project17/templates/rango/index.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Index Page{% endblock %}

{% block body_block %}
        <!--1.  This bit is to test your_name view -->
        {% if yourName %}
            <strong>You gave me your name as {{yourName}}</strong><br />
        {% endif %}

         <!-- 2. displays logged in users name -->
        <div class="page-header">
         {% if user.is_authenticated %}

                <h1>Rango says... hello {{ user.username }}!</h1>
         {% else %}
                <h1>Rango says... hello world!</h1>
          {% endif %}
         </div>

           <!-- 3. To show list of categories for all users-->
        <div class="row placeholders">
            <div class="col-xs-12 col-sm-6 placeholder">

                {% if categories %}
                <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"> Categories </h3>
                </div>
                </div>
                    <ul class="list-group">
                        {% for category in categories %}
                        <!--li><a href="/rango/category/{{ category.slug }}/"> {{ category.name }}</a> </li-->
                        <li class="list-group-item"><a href="{% url 'category'  category.slug %}"> {{ category.name }}</a> </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no categories present. </strong>
                {% endif %}

            </div>

            <div class="col-xs-12 col-sm-6 placeholder">
                {% if pages %}

                    <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Top 5 Pages</h3>
                    </div>
                    </div>

                    <ul class="list-group">
                        {% for page in pages %}
                        <!--li><a href="/rango/category/{{ category.slug }}/"> {{ category.name }}</a> </li-->
                        <li class="list-group-item"><a href="{{ page.url }}"> {{ page.title }} - {{ page.category.name }} ({{ page.views }} view(s))</a> </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no pages present. </strong>
                {% endif %}

            </div>
        </div>

        <strong> BTW, number of times you visited rango was {{ visits }}</strong>
        <!--img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /-->

{% endblock %}